-- Auto-generated from schema-map-postgres.yaml (map@74ce4f4)
-- engine: postgres
-- table:  schema_registry

CREATE TABLE IF NOT EXISTS schema_registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_name VARCHAR(120) NOT NULL,
  component   VARCHAR(120) NOT NULL,           -- 'db','rbac','api',...
  version     VARCHAR(64) NOT NULL,
  checksum    VARCHAR(64) NULL,
  applied_at  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  meta JSONB NULL,
  CONSTRAINT uq_schema_version UNIQUE (system_name, component, version)
);
